/**
 * The behaviour snapshot recorded in A0: how selected campaign levels and a
 * fixed-seed Endless run start. `npm run baseline` writes it to
 * tests/fixtures/baseline.json, and tests/unit/baseline.test.ts fails if any
 * later change alters level data, wave generation, the balance model, the
 * solver's hint or the scoring maths without the golden file being
 * deliberately regenerated (and the ruleset/generator version bumped).
 */

import { GRACE_MS } from '../../src/game/config';
import { generateWave } from '../../src/game/levels/generator';
import { getLevel } from '../../src/game/levels/levels';
import type { LevelDef } from '../../src/game/levels/types';
import { evaluate } from '../../src/game/systems/BalanceSystem';
import { scoreWave } from '../../src/game/systems/RunManager';
import { hintFor, solve } from '../../src/game/systems/Solver';

export const BASELINE_LEVELS = [1, 8, 15, 25];
export const BASELINE_SEED = 12345;
export const BASELINE_WAVES = [1, 10, 25];

function levelStart(level: LevelDef) {
  const ids = level.packages.map((_, i) => i);
  const empty = evaluate(level, []);
  const inOrder = solve(level, [], ids, { nodeBudget: 1_500_000, prefixLimit: level.balanceTolerance });
  const hint = hintFor(level, [], ids, 0);
  return {
    shelves: level.shelves,
    packages: level.packages,
    balanceTolerance: level.balanceTolerance,
    finalBalanceMax: level.finalBalanceMax ?? null,
    queue: ids,
    emptyBoard: {
      status: empty.status,
      imbalance: empty.imbalance,
      shelfWeights: empty.shelfWeights,
    },
    firstHint: hint,
    conveyorOrderSolvable: inOrder.ok,
    conveyorOrderSolution: inOrder.placements,
  };
}

export function buildBaseline() {
  return {
    note: 'Generated by `npm run baseline`. Regenerate only on a deliberate rules/content change.',
    graceMs: GRACE_MS,
    campaign: BASELINE_LEVELS.map((id) => {
      const level = getLevel(id);
      return { id, name: level.name, ...levelStart(level) };
    }),
    endless: {
      seed: BASELINE_SEED,
      waves: BASELINE_WAVES.map((wave) => {
        const plan = generateWave(BASELINE_SEED, wave);
        return {
          wave,
          graceScale: plan.graceScale,
          attempts: plan.attempts,
          fallback: plan.fallback,
          objective: plan.objective,
          solution: plan.solution,
          ...levelStart(plan.level),
        };
      }),
    },
    scoring: [
      scoreWave({ wave: 1, manifestWeight: 6, imbalance: 0, tolerance: 7, mistakes: 0, hintUsed: false }),
      scoreWave({ wave: 10, manifestWeight: 24, imbalance: 2.5, tolerance: 5, mistakes: 1, hintUsed: false }),
      scoreWave({ wave: 25, manifestWeight: 30, imbalance: 1, tolerance: 3, mistakes: 0, hintUsed: true }),
    ],
  };
}
